name: exoskeleton_suit_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial:
    path: flutter_bluetooth_serial
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  syncfusion_flutter_sliders: ^29.1.38
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  


flutter:
  uses-material-design: true

  fonts:
    - family: Golos_Text
      fonts:
        - asset: assets/fonts/GolosText-ExtraBold.ttf
          weight: 800
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400
    - family: Federant
      fonts:
        - asset: assets/fonts/Federant-Regular.ttf
          weight: 700
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
          weight: 900
    - family: Caveat_Bold
      fonts: 
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/models/


    
    
